[package]
name = "rust-bot"
version = "0.1.0"
authors = ["chenkail <40770208+Chenkail@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.8.0"
serenity = { version = "0.9.3", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "0.2", features = ["macros"] }
